### ISSUE TITLE
Add option that allows a client to download the alternate certificate link instead of the default one

### ISSUE THREAD

**Issue by TJP85** [acmephp/acmephp#210]
Hello. First, I just wanted to thank you for the great work that's been done on this library. Also, any time that you can spare to review this Pull Request would be greatly appreciated. 

With the upcoming changes to Let's Encrypt transitioning to using their ISRG Root X1 for signing certificates instead of the one that is cross-signed with IdenTrust’s DST Root X3, they have provided a feature that allows clients to request an alternate certificate that is still cross signed with IdenTrust’s DST Root X3. It looks like these changes have been pushed back to Jan 2021 for now, but this feature would be great for those clients that still want to support SSL Certificates for older Android devices that do not have Let's Encrypt's new ISRG Root X1 as a trusted CA. 

Thanks again for your time.

https://github.com/acmephp/acmephp/pull/209

https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html
https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-jan-11-2021/125516

**Comment by jaykaypea** [comment]
Hi! Jenessa from Let's Encrypt here, just seconding this as it's a cool feature to have in general, but especially with this change! You can see more how certbot did it here: https://github.com/certbot/certbot/pull/8080

If you have any questions or need help with the feature, many of our community ACME client developers are on our forum and can answer questions! community.letsencrypt.org

And THANK YOU for maintaining this great client. The Web is better for it because of you, and the work you are doing definitely does not go unnoticed. Thank you, thank you, thank you.

**Comment by tgalopin** [comment]
Hi!

I'm currently working on AcmePHP 2.0 (release in upcoming days/weeks), I'll have a look in that context :) .

**Comment by tgalopin** [comment]
Thanks for your help on that. I merged it in 2.0 and added tests, I'm confident it's working well. I'll release it soon :) .
