### ISSUE TITLE
In the config, what is "install", example is for AWS, what about shared hosting?

### ISSUE THREAD

**Issue by tinonetic** [acmephp/acmephp#248]
Hi,

I'm going through the [config.yml example](https://acmephp.github.io/documentation/getting-started/2-obtain-certificate-easy.html)

In the **install** section I see the example is specific to AWS hosting... what would I put in a shared hosting environment?

![image](https://user-images.githubusercontent.com/8109147/139580017-70862991-8b90-4d19-afb5-aa98c499e843.png)

Thanks in advance for your help!

**Comment by camlafit** [comment]
Hello

Following source code, available modes are listed at https://github.com/acmephp/acmephp/tree/master/src/Cli/Action
But I'm not any idea about deploy on shared hosting

**Comment by SamMousa** [comment]
Closing this due to old age.

**Comment by camlafit** [comment]
Hello

Any official response was done and looks always actual. 
Old age doesn't look a good reason to close this issue.

Thanks

**Comment by SamMousa** [comment]
I'm sorry @camlafit this issue was left here without anyone finding the time / priority to work on it. We have some new effort on the project now and we should focus it on recent issues. 
I cannot imagine someone waiting 3+ years without a solution or workaround for this. Reactions like yours feel like they are more out of principle than anything else.
If you want to work on it or open a new issue with more details feel free.

**Comment by camlafit** [comment]
Hello

Yes  my remark can be consider only as a principle comment.

Last year, I've tried to work on this project and check many issue to compare them with my different trouble and search to understand logic behind. 

In this case, this issue was accurate 3 years ago.  It was always accurate when I try to provide a starting point to find a workaround. Looks actually always valid.

To have old issues is not a trouble. I know some project with very old issues, 3 years is not a so long delay :)
For example was also possible to label it as "see to later" / "priority low" / ...  and focus on recent or important issue.

In all case it's nice to see a new life about this project :)

Thanks a lot

**Comment by SamMousa** [comment]
> To have old issues is not a trouble.

That is really subjective; having a very large to do list is demotivating to some people, especially as many of those items are old which makes it more likely that the original poster is no longer actively worried about it.

> Last year, I've tried to work on this project and check many issue to compare them with my different trouble and search to understand logic behind.

This is what I'm trying to solve by creating a cleaner developer experience: more checks, more automation, less freedom. One part of this, for me, is cleaning up inactive issues.
