### ISSUE TITLE
Another question about the http-01 payload / contents

### ISSUE THREAD

**Issue by kevinquinnyo** [acmephp/acmephp#3]
@tgalopin Preface:  Sorry again for asking a question as opposed to presenting a code issue here, but you were helpful the last time and I've hit a brick wall today.

So basically I'm using this library as part of another application I'm building, so I'm storing the various object data into mysql.

I think I have all of that working, but I can't seem to figure out something basic about letsencrypt/acme.

For the http-01 challenge, I'm supposed to provision a file at say `http://example.com/.well-known/acme-challenge/$token` and it's contents should be... what exactly?

Looking through your test cases (since that's better than documentation sometimes) I see that you are putting the "payload" into the file:

https://github.com/acmephp/acmephp/blob/master/tests/Core/AcmeClientTest.php#L131

So if that's true, then the file should contain something like:

`qu6WeClKmrROn0d9_gdbs0hgRtwyXeCScBt031mulKI.hS9kK3SM_bfmYvDYe-JjxWbrQL6eSjBdY4p9XnIZqDQ`

and that's it.  Is that right?

That doesn't work for me, and I'm not sure if I'm doing something wrong, or it's a complete misunderstanding of Acme/LetsEncrypt.  But even if that's what I'm supposed to do, that doesn't match the test case in the LetsEncrypt's `certbot` test here:

https://github.com/certbot/certbot/blob/e5876ea162c22e9b2fff8cfcb7373a57572f3515/acme/acme/challenges_test.py#L153

And it doesn't match the information in the SPEC here:

https://letsencrypt.github.io/acme-spec/#rfc.section.7.1

So what am I missing exactly?  Sorry to trouble you with a question, but I've tried to figure this out for way too long and I feel like you might be able to help me.  Thanks so much in advance if you can shed some light on this for me.

**Comment by tgalopin** [comment]
Hi @kevinquinnyo !

That's a very interesting question indeed :) ! Thanks for your interest in the library and for your feedbacks, that's really appreciated!

What is important to note here is that the ACME protocol is still not yet fully stable. While the document you linked is still mostly valid, the protocol has changed since then (and I think it's a link from the documentation, I should change that :) ). You can see on top of it that the document you linked expired on 22/01/2016.

I suggest you read the last version of the protocol, defined at https://tools.ietf.org/html/draft-ietf-acme-acme-02 (and expiring in september), especially this part: https://tools.ietf.org/html/draft-ietf-acme-acme-02#section-7.2.

As you can see at line https://github.com/acmephp/acmephp/blob/master/src/Core/AcmeClient.php#L125, we are not using the `simpleHttp` challenge but the `http-01` one, defined in the new protocol version as:

```
The path at which the resource is provisioned is comprised of the
fixed prefix ".well-known/acme-challenge/", followed by the "token"
value in the challenge.  The value of the resource MUST be the ASCII
representation of the key authorization.
```

And we are doing that by encoding the account key here: https://github.com/acmephp/acmephp/blob/master/src/Core/AcmeClient.php#L115

The payload we provide using the AcmeClient class is this `ASCII
representation of the key authorization`.

I hope this answer your question :) . Don't hesitate to ask if you have another issue, I would be glad to give a hand when you need it.

PS : you can close this if you this answer your issue :) .

**Comment by kevinquinnyo** [comment]
@tgalopin Thanks!  That was incredibly helpful and clears it up 100% for me.
