### ISSUE TITLE
AcmePhp\Ssl\Exception\KeyPairGenerationException on register

### ISSUE THREAD

**Issue by samlittler** [acmephp/acmephp#69]
I'm trying to use this software on Windows Server (unfortunately) and when running the following command I get an exception I can't figure out.

`php acmephp.phar register redacted@example.com`

Which throws out the following output.

    No account key pair was found, generating one...
    
    
      [AcmePhp\Ssl\Exception\KeyPairGenerationException]
      OpenSSL key creation failed during generation with error: error:02001003:sy
      stem library:fopen:No such process
    
    
    register [--agreement AGREEMENT] [--] [<email>]

**Comment by crossjoin** [comment]
I had the same problem and could fix this by setting the OPENSSL_CONF environment variable, as described here: http://php.net/manual/en/openssl.installation.php

After that I got a CURL error (curl: (60) SSL certificate : unable to get local issuer certificate), which can be fixed by downloading the file https://curl.haxx.se/ca/cacert.pem and configuring it in the php.ini (setting curl.cainfo).

**Comment by mkoske** [comment]
I had similar issue, but got it fixed by adding OPENSSL_CONF environment variable as @crossjoin did.

PHP had an example file distributed with it, but what should be put in that file? How to configure it correctly?

**Comment by tgalopin** [comment]
Do you have other issues with OpenSSL in your applications? I don't think this is related to Acme PHP.

**Comment by jderusse** [comment]
I suggest to use the docker image that work out of box and embed all the require dependencies
