### ISSUE TITLE
Access to authorization expiration date?

### ISSUE THREAD

**Issue by philipsharp** [acmephp/acmephp#88]
Use the AcmePHP Core library I would like to have access to the authorization expiration date.

To do this I would expect that `AcmeClient::requestAuthorization()` and `AcmeClient::challengeAuthorization()` would return authorization objects, not just the challenges. I realize that this would be a BC-breaking change for the library, although not necessarily for the CLI client.

Additionally, my reading of the current ACME spec (Draft 9, section 7.5.1) is that the polling should be done on the authorization URL, not the challenge URL as `AcmeClient::challengeAuthorization()` is currently implemented. Passing the authorization object to that method would make this possible.

**Comment by jderusse** [comment]
At time you write the issue, the application supported acme V1, but you are referencing draft 9 (acme v2).
Now, acme have been updated to support acme v2, and I've made some changes and expose new interfaces for BC, can you have a second look to your issue?

**Comment by philipsharp** [comment]
@jderusse That was my mistake for referencing the newer draft, although the language "the client will need to poll the authorization resource to see when it is finalized" is in all the drafts back to 0.

I will write a test script to see if the v2 changes allow me to get this data. At first glance the `CertificateOrder` looks like the right object but this implementation doesn't have the order metadata: https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-7.1.3

**Comment by jderusse** [comment]
The expirity is not return in the new CertificateOrder object. I didn't have to use it because I noticed that each time I request a new Order, let's encrypt returns eithre
 - a new AuthorizationChallenge in state pending
- a previous alreadu validated AuthorizationChallenge

In the second case, I didn't have to re-validate it, the new implementation of acme-php just need to validate fresh pending auth.

If you really need this argument, submit a PR? I'll be happy to merge it :)

**Comment by philipsharp** [comment]
I'm still looking into this and hope to have an answer this week.
